source 'https://rubygems.org'

gem 'sinatra'
gem 'dashing-jruby'
gem 'twitter', '>= 5.9.0'
gem 'jira-ruby', :require => 'jira'
gem 'json'
gem 'icalendar'
gem 'google-api-client'
gem 'security'
gem 'mail'
gem 'dashing_storage'
gem 'haml'
gem 'mongo'
gem 'bson_ext'
gem 'net'
